# This file configures the analyzer for E-Learning QC App
# Standalone configuration without external dependencies

analyzer:
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing return as errors
    missing_return: error
    # Allow TODO comments
    todo: ignore
    # Allow deprecated member use during development
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
  
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"

linter:
  rules:
    # Disable rules that cause unnecessary warnings
    avoid_print: false  # Allow print statements for debugging
    prefer_const_constructors: false  # Allow non-const constructors
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false  # Allow widgets without key
    sized_box_for_whitespace: false
    avoid_unnecessary_containers: false
    prefer_const_declarations: false
    
    # Enable important rules
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    always_declare_return_types: true
    
    # Code style (optional, adjust as needed)
    # prefer_single_quotes: true
    # require_trailing_commas: true
